# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.notification_resource import NotificationResource

class TestNotificationResource(unittest.TestCase):
    """NotificationResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationResource:
        """Test NotificationResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationResource`
        """
        model = NotificationResource()
        if include_optional:
            return NotificationResource(
                id = 56,
                name = '',
                fields = [
                    sonarr_api.models.field.Field(
                        order = 56, 
                        name = '', 
                        label = '', 
                        unit = '', 
                        help_text = '', 
                        help_text_warning = '', 
                        help_link = '', 
                        value = null, 
                        type = '', 
                        advanced = True, 
                        select_options = [
                            sonarr_api.models.select_option.SelectOption(
                                value = 56, 
                                name = '', 
                                order = 56, 
                                hint = '', )
                            ], 
                        select_options_provider_action = '', 
                        section = '', 
                        hidden = '', 
                        privacy = 'normal', 
                        placeholder = '', 
                        is_float = True, )
                    ],
                implementation_name = '',
                implementation = '',
                config_contract = '',
                info_link = '',
                message = sonarr_api.models.provider_message.ProviderMessage(
                    message = '', 
                    type = 'info', ),
                tags = [
                    56
                    ],
                presets = [
                    sonarr_api.models.notification_resource.NotificationResource(
                        id = 56, 
                        name = '', 
                        fields = [
                            sonarr_api.models.field.Field(
                                order = 56, 
                                name = '', 
                                label = '', 
                                unit = '', 
                                help_text = '', 
                                help_text_warning = '', 
                                help_link = '', 
                                value = null, 
                                type = '', 
                                advanced = True, 
                                select_options = [
                                    sonarr_api.models.select_option.SelectOption(
                                        value = 56, 
                                        name = '', 
                                        order = 56, 
                                        hint = '', )
                                    ], 
                                select_options_provider_action = '', 
                                section = '', 
                                hidden = '', 
                                privacy = 'normal', 
                                placeholder = '', 
                                is_float = True, )
                            ], 
                        implementation_name = '', 
                        implementation = '', 
                        config_contract = '', 
                        info_link = '', 
                        message = sonarr_api.models.provider_message.ProviderMessage(
                            type = 'info', ), 
                        tags = [
                            56
                            ], 
                        presets = [
                            sonarr_api.models.notification_resource.NotificationResource(
                                id = 56, 
                                name = '', 
                                implementation_name = '', 
                                implementation = '', 
                                config_contract = '', 
                                info_link = '', 
                                link = '', 
                                on_grab = True, 
                                on_download = True, 
                                on_upgrade = True, 
                                on_import_complete = True, 
                                on_rename = True, 
                                on_series_add = True, 
                                on_series_delete = True, 
                                on_episode_file_delete = True, 
                                on_episode_file_delete_for_upgrade = True, 
                                on_health_issue = True, 
                                include_health_warnings = True, 
                                on_health_restored = True, 
                                on_application_update = True, 
                                on_manual_interaction_required = True, 
                                supports_on_grab = True, 
                                supports_on_download = True, 
                                supports_on_upgrade = True, 
                                supports_on_import_complete = True, 
                                supports_on_rename = True, 
                                supports_on_series_add = True, 
                                supports_on_series_delete = True, 
                                supports_on_episode_file_delete = True, 
                                supports_on_episode_file_delete_for_upgrade = True, 
                                supports_on_health_issue = True, 
                                supports_on_health_restored = True, 
                                supports_on_application_update = True, 
                                supports_on_manual_interaction_required = True, 
                                test_command = '', )
                            ], 
                        link = '', 
                        on_grab = True, 
                        on_download = True, 
                        on_upgrade = True, 
                        on_import_complete = True, 
                        on_rename = True, 
                        on_series_add = True, 
                        on_series_delete = True, 
                        on_episode_file_delete = True, 
                        on_episode_file_delete_for_upgrade = True, 
                        on_health_issue = True, 
                        include_health_warnings = True, 
                        on_health_restored = True, 
                        on_application_update = True, 
                        on_manual_interaction_required = True, 
                        supports_on_grab = True, 
                        supports_on_download = True, 
                        supports_on_upgrade = True, 
                        supports_on_import_complete = True, 
                        supports_on_rename = True, 
                        supports_on_series_add = True, 
                        supports_on_series_delete = True, 
                        supports_on_episode_file_delete = True, 
                        supports_on_episode_file_delete_for_upgrade = True, 
                        supports_on_health_issue = True, 
                        supports_on_health_restored = True, 
                        supports_on_application_update = True, 
                        supports_on_manual_interaction_required = True, 
                        test_command = '', )
                    ],
                link = '',
                on_grab = True,
                on_download = True,
                on_upgrade = True,
                on_import_complete = True,
                on_rename = True,
                on_series_add = True,
                on_series_delete = True,
                on_episode_file_delete = True,
                on_episode_file_delete_for_upgrade = True,
                on_health_issue = True,
                include_health_warnings = True,
                on_health_restored = True,
                on_application_update = True,
                on_manual_interaction_required = True,
                supports_on_grab = True,
                supports_on_download = True,
                supports_on_upgrade = True,
                supports_on_import_complete = True,
                supports_on_rename = True,
                supports_on_series_add = True,
                supports_on_series_delete = True,
                supports_on_episode_file_delete = True,
                supports_on_episode_file_delete_for_upgrade = True,
                supports_on_health_issue = True,
                supports_on_health_restored = True,
                supports_on_application_update = True,
                supports_on_manual_interaction_required = True,
                test_command = ''
            )
        else:
            return NotificationResource(
        )
        """

    def testNotificationResource(self):
        """Test NotificationResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
