# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.api.queue_action_api import QueueActionApi


class TestQueueActionApi(unittest.TestCase):
    """QueueActionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QueueActionApi()

    def tearDown(self) -> None:
        pass

    def test_api_v3_queue_grab_bulk_post(self) -> None:
        """Test case for api_v3_queue_grab_bulk_post

        """
        pass

    def test_api_v3_queue_grab_id_post(self) -> None:
        """Test case for api_v3_queue_grab_id_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
