# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.media_management_config_resource import MediaManagementConfigResource

class TestMediaManagementConfigResource(unittest.TestCase):
    """MediaManagementConfigResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MediaManagementConfigResource:
        """Test MediaManagementConfigResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MediaManagementConfigResource`
        """
        model = MediaManagementConfigResource()
        if include_optional:
            return MediaManagementConfigResource(
                id = 56,
                auto_unmonitor_previously_downloaded_episodes = True,
                recycle_bin = '',
                recycle_bin_cleanup_days = 56,
                download_propers_and_repacks = 'preferAndUpgrade',
                create_empty_series_folders = True,
                delete_empty_folders = True,
                file_date = 'none',
                rescan_after_refresh = 'always',
                set_permissions_linux = True,
                chmod_folder = '',
                chown_group = '',
                episode_title_required = 'always',
                skip_free_space_check_when_importing = True,
                minimum_free_space_when_importing = 56,
                copy_using_hardlinks = True,
                use_script_import = True,
                script_import_path = '',
                import_extra_files = True,
                extra_file_extensions = '',
                enable_media_info = True
            )
        else:
            return MediaManagementConfigResource(
        )
        """

    def testMediaManagementConfigResource(self):
        """Test MediaManagementConfigResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
