# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.list_sync_level_type import ListSyncLevelType

class TestListSyncLevelType(unittest.TestCase):
    """ListSyncLevelType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListSyncLevelType(self):
        """Test ListSyncLevelType"""
        # inst = ListSyncLevelType()

if __name__ == '__main__':
    unittest.main()
