# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.series_editor_resource import SeriesEditorResource

class TestSeriesEditorResource(unittest.TestCase):
    """SeriesEditorResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SeriesEditorResource:
        """Test SeriesEditorResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SeriesEditorResource`
        """
        model = SeriesEditorResource()
        if include_optional:
            return SeriesEditorResource(
                series_ids = [
                    56
                    ],
                monitored = True,
                monitor_new_items = 'all',
                quality_profile_id = 56,
                series_type = 'standard',
                season_folder = True,
                root_folder_path = '',
                tags = [
                    56
                    ],
                apply_tags = 'add',
                move_files = True,
                delete_files = True,
                add_import_list_exclusion = True
            )
        else:
            return SeriesEditorResource(
        )
        """

    def testSeriesEditorResource(self):
        """Test SeriesEditorResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
