# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.command_resource import CommandResource

class TestCommandResource(unittest.TestCase):
    """CommandResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommandResource:
        """Test CommandResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommandResource`
        """
        model = CommandResource()
        if include_optional:
            return CommandResource(
                id = 56,
                name = '',
                command_name = '',
                message = '',
                body = sonarr_api.models.command.Command(
                    send_updates_to_client = True, 
                    update_scheduled_task = True, 
                    completion_message = '', 
                    requires_disk_access = True, 
                    is_exclusive = True, 
                    is_long_running = True, 
                    name = '', 
                    last_execution_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    trigger = 'unspecified', 
                    suppress_messages = True, 
                    client_user_agent = '', ),
                priority = 'normal',
                status = 'queued',
                result = 'unknown',
                queued = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                started = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ended = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                duration = '',
                exception = '',
                trigger = 'unspecified',
                client_user_agent = '',
                state_change_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                send_updates_to_client = True,
                update_scheduled_task = True,
                last_execution_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CommandResource(
        )
        """

    def testCommandResource(self):
        """Test CommandResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
