# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.localization_language_resource import LocalizationLanguageResource

class TestLocalizationLanguageResource(unittest.TestCase):
    """LocalizationLanguageResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocalizationLanguageResource:
        """Test LocalizationLanguageResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocalizationLanguageResource`
        """
        model = LocalizationLanguageResource()
        if include_optional:
            return LocalizationLanguageResource(
                identifier = ''
            )
        else:
            return LocalizationLanguageResource(
        )
        """

    def testLocalizationLanguageResource(self):
        """Test LocalizationLanguageResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
