# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.auto_tagging_specification_schema import AutoTaggingSpecificationSchema

class TestAutoTaggingSpecificationSchema(unittest.TestCase):
    """AutoTaggingSpecificationSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutoTaggingSpecificationSchema:
        """Test AutoTaggingSpecificationSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutoTaggingSpecificationSchema`
        """
        model = AutoTaggingSpecificationSchema()
        if include_optional:
            return AutoTaggingSpecificationSchema(
                id = 56,
                name = '',
                implementation = '',
                implementation_name = '',
                negate = True,
                required = True,
                fields = [
                    sonarr_api.models.field.Field(
                        order = 56, 
                        name = '', 
                        label = '', 
                        unit = '', 
                        help_text = '', 
                        help_text_warning = '', 
                        help_link = '', 
                        value = null, 
                        type = '', 
                        advanced = True, 
                        select_options = [
                            sonarr_api.models.select_option.SelectOption(
                                value = 56, 
                                name = '', 
                                order = 56, 
                                hint = '', )
                            ], 
                        select_options_provider_action = '', 
                        section = '', 
                        hidden = '', 
                        privacy = 'normal', 
                        placeholder = '', 
                        is_float = True, )
                    ]
            )
        else:
            return AutoTaggingSpecificationSchema(
        )
        """

    def testAutoTaggingSpecificationSchema(self):
        """Test AutoTaggingSpecificationSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
