# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.rename_episode_resource import RenameEpisodeResource

class TestRenameEpisodeResource(unittest.TestCase):
    """RenameEpisodeResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RenameEpisodeResource:
        """Test RenameEpisodeResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RenameEpisodeResource`
        """
        model = RenameEpisodeResource()
        if include_optional:
            return RenameEpisodeResource(
                id = 56,
                series_id = 56,
                season_number = 56,
                episode_numbers = [
                    56
                    ],
                episode_file_id = 56,
                existing_path = '',
                new_path = ''
            )
        else:
            return RenameEpisodeResource(
        )
        """

    def testRenameEpisodeResource(self):
        """Test RenameEpisodeResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
