# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.api.update_log_file_api import UpdateLogFileApi


class TestUpdateLogFileApi(unittest.TestCase):
    """UpdateLogFileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UpdateLogFileApi()

    def tearDown(self) -> None:
        pass

    def test_api_v3_log_file_update_filename_get(self) -> None:
        """Test case for api_v3_log_file_update_filename_get

        """
        pass

    def test_api_v3_log_file_update_get(self) -> None:
        """Test case for api_v3_log_file_update_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
