# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.media_info_resource import MediaInfoResource

class TestMediaInfoResource(unittest.TestCase):
    """MediaInfoResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MediaInfoResource:
        """Test MediaInfoResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MediaInfoResource`
        """
        model = MediaInfoResource()
        if include_optional:
            return MediaInfoResource(
                id = 56,
                audio_bitrate = 56,
                audio_channels = 1.337,
                audio_codec = '',
                audio_languages = '',
                audio_stream_count = 56,
                video_bit_depth = 56,
                video_bitrate = 56,
                video_codec = '',
                video_fps = 1.337,
                video_dynamic_range = '',
                video_dynamic_range_type = '',
                resolution = '',
                run_time = '',
                scan_type = '',
                subtitles = ''
            )
        else:
            return MediaInfoResource(
        )
        """

    def testMediaInfoResource(self):
        """Test MediaInfoResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
