# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.tag_details_resource import TagDetailsResource

class TestTagDetailsResource(unittest.TestCase):
    """TagDetailsResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagDetailsResource:
        """Test TagDetailsResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagDetailsResource`
        """
        model = TagDetailsResource()
        if include_optional:
            return TagDetailsResource(
                id = 56,
                label = '',
                delay_profile_ids = [
                    56
                    ],
                import_list_ids = [
                    56
                    ],
                notification_ids = [
                    56
                    ],
                restriction_ids = [
                    56
                    ],
                indexer_ids = [
                    56
                    ],
                download_client_ids = [
                    56
                    ],
                auto_tag_ids = [
                    56
                    ],
                series_ids = [
                    56
                    ]
            )
        else:
            return TagDetailsResource(
        )
        """

    def testTagDetailsResource(self):
        """Test TagDetailsResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
