# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.delay_profile_resource import DelayProfileResource

class TestDelayProfileResource(unittest.TestCase):
    """DelayProfileResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DelayProfileResource:
        """Test DelayProfileResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DelayProfileResource`
        """
        model = DelayProfileResource()
        if include_optional:
            return DelayProfileResource(
                id = 56,
                enable_usenet = True,
                enable_torrent = True,
                preferred_protocol = 'unknown',
                usenet_delay = 56,
                torrent_delay = 56,
                bypass_if_highest_quality = True,
                bypass_if_above_custom_format_score = True,
                minimum_custom_format_score = 56,
                order = 56,
                tags = [
                    56
                    ]
            )
        else:
            return DelayProfileResource(
        )
        """

    def testDelayProfileResource(self):
        """Test DelayProfileResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
