# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.import_list_bulk_resource import ImportListBulkResource

class TestImportListBulkResource(unittest.TestCase):
    """ImportListBulkResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportListBulkResource:
        """Test ImportListBulkResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportListBulkResource`
        """
        model = ImportListBulkResource()
        if include_optional:
            return ImportListBulkResource(
                ids = [
                    56
                    ],
                tags = [
                    56
                    ],
                apply_tags = 'add',
                enable_automatic_add = True,
                root_folder_path = '',
                quality_profile_id = 56
            )
        else:
            return ImportListBulkResource(
        )
        """

    def testImportListBulkResource(self):
        """Test ImportListBulkResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
