# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.api.import_list_exclusion_api import ImportListExclusionApi


class TestImportListExclusionApi(unittest.TestCase):
    """ImportListExclusionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImportListExclusionApi()

    def tearDown(self) -> None:
        pass

    def test_api_v3_importlistexclusion_bulk_delete(self) -> None:
        """Test case for api_v3_importlistexclusion_bulk_delete

        """
        pass

    def test_api_v3_importlistexclusion_get(self) -> None:
        """Test case for api_v3_importlistexclusion_get

        """
        pass

    def test_api_v3_importlistexclusion_id_delete(self) -> None:
        """Test case for api_v3_importlistexclusion_id_delete

        """
        pass

    def test_api_v3_importlistexclusion_id_get(self) -> None:
        """Test case for api_v3_importlistexclusion_id_get

        """
        pass

    def test_api_v3_importlistexclusion_id_put(self) -> None:
        """Test case for api_v3_importlistexclusion_id_put

        """
        pass

    def test_api_v3_importlistexclusion_paged_get(self) -> None:
        """Test case for api_v3_importlistexclusion_paged_get

        """
        pass

    def test_api_v3_importlistexclusion_post(self) -> None:
        """Test case for api_v3_importlistexclusion_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
