# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.series_resource import SeriesResource

class TestSeriesResource(unittest.TestCase):
    """SeriesResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SeriesResource:
        """Test SeriesResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SeriesResource`
        """
        model = SeriesResource()
        if include_optional:
            return SeriesResource(
                id = 56,
                title = '',
                alternate_titles = [
                    sonarr_api.models.alternate_title_resource.AlternateTitleResource(
                        title = '', 
                        season_number = 56, 
                        scene_season_number = 56, 
                        scene_origin = '', 
                        comment = '', )
                    ],
                sort_title = '',
                status = 'continuing',
                ended = True,
                profile_name = '',
                overview = '',
                next_airing = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                previous_airing = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                network = '',
                air_time = '',
                images = [
                    sonarr_api.models.media_cover.MediaCover(
                        cover_type = 'unknown', 
                        url = '', 
                        remote_url = '', )
                    ],
                original_language = sonarr_api.models.language.Language(
                    id = 56, 
                    name = '', ),
                remote_poster = '',
                seasons = [
                    sonarr_api.models.season_resource.SeasonResource(
                        season_number = 56, 
                        monitored = True, 
                        statistics = sonarr_api.models.season_statistics_resource.SeasonStatisticsResource(
                            next_airing = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            previous_airing = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            episode_file_count = 56, 
                            episode_count = 56, 
                            total_episode_count = 56, 
                            size_on_disk = 56, 
                            release_groups = [
                                ''
                                ], 
                            percent_of_episodes = 1.337, ), 
                        images = [
                            sonarr_api.models.media_cover.MediaCover(
                                cover_type = 'unknown', 
                                url = '', 
                                remote_url = '', )
                            ], )
                    ],
                year = 56,
                path = '',
                quality_profile_id = 56,
                season_folder = True,
                monitored = True,
                monitor_new_items = 'all',
                use_scene_numbering = True,
                runtime = 56,
                tvdb_id = 56,
                tv_rage_id = 56,
                tv_maze_id = 56,
                tmdb_id = 56,
                first_aired = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_aired = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                series_type = 'standard',
                clean_title = '',
                imdb_id = '',
                title_slug = '',
                root_folder_path = '',
                folder = '',
                certification = '',
                genres = [
                    ''
                    ],
                tags = [
                    56
                    ],
                added = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                add_options = sonarr_api.models.add_series_options.AddSeriesOptions(
                    ignore_episodes_with_files = True, 
                    ignore_episodes_without_files = True, 
                    monitor = 'unknown', 
                    search_for_missing_episodes = True, 
                    search_for_cutoff_unmet_episodes = True, ),
                ratings = sonarr_api.models.ratings.Ratings(
                    votes = 56, 
                    value = 1.337, ),
                statistics = sonarr_api.models.series_statistics_resource.SeriesStatisticsResource(
                    season_count = 56, 
                    episode_file_count = 56, 
                    episode_count = 56, 
                    total_episode_count = 56, 
                    size_on_disk = 56, 
                    release_groups = [
                        ''
                        ], 
                    percent_of_episodes = 1.337, ),
                episodes_changed = True,
                language_profile_id = 56
            )
        else:
            return SeriesResource(
        )
        """

    def testSeriesResource(self):
        """Test SeriesResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
