# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.parsed_episode_info import ParsedEpisodeInfo

class TestParsedEpisodeInfo(unittest.TestCase):
    """ParsedEpisodeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ParsedEpisodeInfo:
        """Test ParsedEpisodeInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ParsedEpisodeInfo`
        """
        model = ParsedEpisodeInfo()
        if include_optional:
            return ParsedEpisodeInfo(
                release_title = '',
                series_title = '',
                series_title_info = sonarr_api.models.series_title_info.SeriesTitleInfo(
                    title = '', 
                    title_without_year = '', 
                    year = 56, 
                    all_titles = [
                        ''
                        ], ),
                quality = sonarr_api.models.quality_model.QualityModel(
                    revision = sonarr_api.models.revision.Revision(
                        version = 56, 
                        real = 56, 
                        is_repack = True, ), ),
                season_number = 56,
                episode_numbers = [
                    56
                    ],
                absolute_episode_numbers = [
                    56
                    ],
                special_absolute_episode_numbers = [
                    1.337
                    ],
                air_date = '',
                languages = [
                    sonarr_api.models.language.Language(
                        id = 56, 
                        name = '', )
                    ],
                full_season = True,
                is_partial_season = True,
                is_multi_season = True,
                is_season_extra = True,
                is_split_episode = True,
                is_mini_series = True,
                special = True,
                release_group = '',
                release_hash = '',
                season_part = 56,
                release_tokens = '',
                daily_part = 56,
                is_daily = True,
                is_absolute_numbering = True,
                is_possible_special_episode = True,
                is_possible_scene_season_special = True,
                release_type = 'unknown'
            )
        else:
            return ParsedEpisodeInfo(
        )
        """

    def testParsedEpisodeInfo(self):
        """Test ParsedEpisodeInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
