# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.quality_profile_resource import QualityProfileResource

class TestQualityProfileResource(unittest.TestCase):
    """QualityProfileResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QualityProfileResource:
        """Test QualityProfileResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QualityProfileResource`
        """
        model = QualityProfileResource()
        if include_optional:
            return QualityProfileResource(
                id = 56,
                name = '',
                upgrade_allowed = True,
                cutoff = 56,
                items = [
                    sonarr_api.models.quality_profile_quality_item_resource.QualityProfileQualityItemResource(
                        id = 56, 
                        name = '', 
                        quality = sonarr_api.models.quality.Quality(
                            id = 56, 
                            name = '', 
                            source = 'unknown', 
                            resolution = 56, ), 
                        items = [
                            sonarr_api.models.quality_profile_quality_item_resource.QualityProfileQualityItemResource(
                                id = 56, 
                                name = '', 
                                allowed = True, )
                            ], 
                        allowed = True, )
                    ],
                min_format_score = 56,
                cutoff_format_score = 56,
                min_upgrade_format_score = 56,
                format_items = [
                    sonarr_api.models.profile_format_item_resource.ProfileFormatItemResource(
                        id = 56, 
                        format = 56, 
                        name = '', 
                        score = 56, )
                    ]
            )
        else:
            return QualityProfileResource(
        )
        """

    def testQualityProfileResource(self):
        """Test QualityProfileResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
