# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.release_resource import ReleaseResource

class TestReleaseResource(unittest.TestCase):
    """ReleaseResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReleaseResource:
        """Test ReleaseResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReleaseResource`
        """
        model = ReleaseResource()
        if include_optional:
            return ReleaseResource(
                id = 56,
                guid = '',
                quality = sonarr_api.models.quality_model.QualityModel(
                    quality = sonarr_api.models.quality.Quality(
                        id = 56, 
                        name = '', 
                        source = 'unknown', 
                        resolution = 56, ), 
                    revision = sonarr_api.models.revision.Revision(
                        version = 56, 
                        real = 56, 
                        is_repack = True, ), ),
                quality_weight = 56,
                age = 56,
                age_hours = 1.337,
                age_minutes = 1.337,
                size = 56,
                indexer_id = 56,
                indexer = '',
                release_group = '',
                sub_group = '',
                release_hash = '',
                title = '',
                full_season = True,
                scene_source = True,
                season_number = 56,
                languages = [
                    sonarr_api.models.language.Language(
                        id = 56, 
                        name = '', )
                    ],
                language_weight = 56,
                air_date = '',
                series_title = '',
                episode_numbers = [
                    56
                    ],
                absolute_episode_numbers = [
                    56
                    ],
                mapped_season_number = 56,
                mapped_episode_numbers = [
                    56
                    ],
                mapped_absolute_episode_numbers = [
                    56
                    ],
                mapped_series_id = 56,
                mapped_episode_info = [
                    sonarr_api.models.release_episode_resource.ReleaseEpisodeResource(
                        id = 56, 
                        season_number = 56, 
                        episode_number = 56, 
                        absolute_episode_number = 56, 
                        title = '', )
                    ],
                approved = True,
                temporarily_rejected = True,
                rejected = True,
                tvdb_id = 56,
                tv_rage_id = 56,
                imdb_id = '',
                rejections = [
                    ''
                    ],
                publish_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                comment_url = '',
                download_url = '',
                info_url = '',
                episode_requested = True,
                download_allowed = True,
                release_weight = 56,
                custom_formats = [
                    sonarr_api.models.custom_format_resource.CustomFormatResource(
                        id = 56, 
                        name = '', 
                        include_custom_format_when_renaming = True, 
                        specifications = [
                            sonarr_api.models.custom_format_specification_schema.CustomFormatSpecificationSchema(
                                id = 56, 
                                name = '', 
                                implementation = '', 
                                implementation_name = '', 
                                info_link = '', 
                                negate = True, 
                                required = True, 
                                fields = [
                                    sonarr_api.models.field.Field(
                                        order = 56, 
                                        name = '', 
                                        label = '', 
                                        unit = '', 
                                        help_text = '', 
                                        help_text_warning = '', 
                                        help_link = '', 
                                        value = null, 
                                        type = '', 
                                        advanced = True, 
                                        select_options = [
                                            sonarr_api.models.select_option.SelectOption(
                                                value = 56, 
                                                name = '', 
                                                order = 56, 
                                                hint = '', )
                                            ], 
                                        select_options_provider_action = '', 
                                        section = '', 
                                        hidden = '', 
                                        privacy = 'normal', 
                                        placeholder = '', 
                                        is_float = True, )
                                    ], 
                                presets = [
                                    sonarr_api.models.custom_format_specification_schema.CustomFormatSpecificationSchema(
                                        id = 56, 
                                        name = '', 
                                        implementation = '', 
                                        implementation_name = '', 
                                        info_link = '', 
                                        negate = True, 
                                        required = True, )
                                    ], )
                            ], )
                    ],
                custom_format_score = 56,
                scene_mapping = sonarr_api.models.alternate_title_resource.AlternateTitleResource(
                    title = '', 
                    season_number = 56, 
                    scene_season_number = 56, 
                    scene_origin = '', 
                    comment = '', ),
                magnet_url = '',
                info_hash = '',
                seeders = 56,
                leechers = 56,
                protocol = 'unknown',
                indexer_flags = 56,
                is_daily = True,
                is_absolute_numbering = True,
                is_possible_special_episode = True,
                special = True,
                series_id = 56,
                episode_id = 56,
                episode_ids = [
                    56
                    ],
                download_client_id = 56,
                download_client = '',
                should_override = True
            )
        else:
            return ReleaseResource(
        )
        """

    def testReleaseResource(self):
        """Test ReleaseResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
