# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.host_config_resource import HostConfigResource

class TestHostConfigResource(unittest.TestCase):
    """HostConfigResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostConfigResource:
        """Test HostConfigResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostConfigResource`
        """
        model = HostConfigResource()
        if include_optional:
            return HostConfigResource(
                id = 56,
                bind_address = '',
                port = 56,
                ssl_port = 56,
                enable_ssl = True,
                launch_browser = True,
                authentication_method = 'none',
                authentication_required = 'enabled',
                analytics_enabled = True,
                username = '',
                password = '',
                password_confirmation = '',
                log_level = '',
                log_size_limit = 56,
                console_log_level = '',
                branch = '',
                api_key = '',
                ssl_cert_path = '',
                ssl_cert_password = '',
                url_base = '',
                instance_name = '',
                application_url = '',
                update_automatically = True,
                update_mechanism = 'builtIn',
                update_script_path = '',
                proxy_enabled = True,
                proxy_type = 'http',
                proxy_hostname = '',
                proxy_port = 56,
                proxy_username = '',
                proxy_password = '',
                proxy_bypass_filter = '',
                proxy_bypass_local_addresses = True,
                certificate_validation = 'enabled',
                backup_folder = '',
                backup_interval = 56,
                backup_retention = 56,
                trust_cgnat_ip_addresses = True
            )
        else:
            return HostConfigResource(
        )
        """

    def testHostConfigResource(self):
        """Test HostConfigResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
