# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonarr_api.models.system_resource import SystemResource

class TestSystemResource(unittest.TestCase):
    """SystemResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemResource:
        """Test SystemResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemResource`
        """
        model = SystemResource()
        if include_optional:
            return SystemResource(
                app_name = '',
                instance_name = '',
                version = '',
                build_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_debug = True,
                is_production = True,
                is_admin = True,
                is_user_interactive = True,
                startup_path = '',
                app_data = '',
                os_name = '',
                os_version = '',
                is_net_core = True,
                is_linux = True,
                is_osx = True,
                is_windows = True,
                is_docker = True,
                mode = 'console',
                branch = '',
                authentication = 'none',
                sqlite_version = '',
                migration_version = 56,
                url_base = '',
                runtime_version = '',
                runtime_name = '',
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                package_version = '',
                package_author = '',
                package_update_mechanism = 'builtIn',
                package_update_mechanism_message = '',
                database_version = '',
                database_type = 'sqLite'
            )
        else:
            return SystemResource(
        )
        """

    def testSystemResource(self):
        """Test SystemResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
